# CMake generated Testfile for 
# Source directory: /mnt/d/vsc_project/TinyWebServer_demo
# Build directory: /mnt/d/vsc_project/TinyWebServer_demo/build_temp_check
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_timer "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_timer")
set_tests_properties(test_timer PROPERTIES  LABELS "smoke;integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_lifecycle "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_lifecycle")
set_tests_properties(test_lifecycle PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_single_connection "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_single_connection")
set_tests_properties(test_single_connection PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_multi_connection "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_multi_connection")
set_tests_properties(test_multi_connection PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_client_close "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_client_close")
set_tests_properties(test_client_close PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_backpressure "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_backpressure")
set_tests_properties(test_backpressure PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_stress "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_stress")
set_tests_properties(test_stress PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_main "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_main")
set_tests_properties(test_main PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_multithread_reactor "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_multithread_reactor")
set_tests_properties(test_multithread_reactor PROPERTIES  LABELS "smoke;integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_basic "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_basic")
set_tests_properties(test_basic PROPERTIES  LABELS "smoke;integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_log "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_log")
set_tests_properties(test_log PROPERTIES  LABELS "smoke;integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_structured_log "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_structured_log")
set_tests_properties(test_structured_log PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_request_validator "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_request_validator")
set_tests_properties(test_request_validator PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_keep_alive "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_keep_alive")
set_tests_properties(test_keep_alive PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_conditional_request "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_conditional_request")
set_tests_properties(test_conditional_request PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_memory_pool "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_memory_pool")
set_tests_properties(test_memory_pool PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_multi_listen_socket "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_multi_listen_socket")
set_tests_properties(test_multi_listen_socket PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_batch_io_handler "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_batch_io_handler")
set_tests_properties(test_batch_io_handler PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
add_test(test_so_reuseport_integration "/mnt/d/vsc_project/TinyWebServer_demo/build_temp_check/test_so_reuseport_integration")
set_tests_properties(test_so_reuseport_integration PROPERTIES  LABELS "integration" TIMEOUT "30" _BACKTRACE_TRIPLES "/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;243;add_test;/mnt/d/vsc_project/TinyWebServer_demo/CMakeLists.txt;0;")
